dataLanguage =[{"paragraph" : "Let me check my chest, my breath right quick (ha) He ain't never seen it in a dress like this (ah) He ain't never even been impressed like this Prolly why I got him quiet on the set like zip Like it, love it, need it bad take it, own it, steal it, fast  in spanish","label" : 0},
       {"paragraph" : "Déjame revisar mi pecho, mi aliento rápido (ja) Nunca lo ha visto en un vestido como este (ah) Nunca ha estado impresionado así Probablemente por eso lo tengo callado en el set, como 'zip' Le gusta, lo ama, lo necesita mucho Tómalo, aduéñate de él, róbalo, rápido", "label" : 1},
       {"paragraph" : "Surfing is a thrilling water sport that captures the essence of freedom and connection to nature. Riding the waves on a surfboard requires skill, balance, and a deep understanding of the ocean's currents. Surfers experience an exhilarating rush as they ride the crest of a wave, feeling the power of the water beneath them. Whether it's the early morning sun glinting off the waves or the sound of the crashing surf, the experience of surfing is both invigorating and calming, creating a unique bond between the surfer and the sea", "label" : 0},
       {"paragraph" : "El surf es un emocionante deporte acuático que captura la esencia de la libertad y la conexión con la naturaleza. Montar las olas en una tabla de surf requiere habilidad, equilibrio y un profundo entendimiento de las corrientes del océano. Los surfistas experimentan una sensación emocionante mientras cabalgan la cresta de una ola, sintiendo la fuerza del agua debajo de ellos. Ya sea el sol de la mañana reflejándose en las olas o el sonido del oleaje rompiendo, la experiencia del surf es a la vez estimulante y tranquilizadora, creando un vínculo único entre el surfista y el mar.", "label" : 1},
       {"paragraph" : "Bees play a crucial role in our ecosystem as pollinators, facilitating the reproduction of many plants and crops that make up a significant portion of our diets. These tiny creatures are remarkable in their ability to collect nectar and pollen from flowers and transform them into honey. Bees live in highly organized colonies, with each member having a specific role to play. However, bees are facing numerous challenges, including habitat loss and pesticide exposure, which threaten their populations. It's essential that we continue to raise awareness about the importance of bees and take steps to protect and preserve their habitats", "label" : 0},
       {"paragraph" : "Las abejas desempeñan un papel crucial en nuestro ecosistema como polinizadores, facilitando la reproducción de muchas plantas y cultivos que forman una parte significativa de nuestra dieta. Estas diminutas criaturas son sorprendentes en su capacidad para recolectar néctar y polen de las flores y transformarlos en miel. Las abejas viven en colonias altamente organizadas, donde cada miembro tiene un papel específico que desempeñar. Sin embargo, las abejas enfrentan numerosos desafíos, incluida la pérdida de hábitat y la exposición a pesticidas, que amenazan sus poblaciones. Es esencial que sigamos creando conciencia sobre la importancia de las abejas y tomemos medidas para proteger y preservar sus hábitats.", "label" : 1},
       {"paragraph" : "I sit and wait Does an angel contemplate my fate and do they know The places where we go When we're grey and old 'Cause I have been told That salvation lets their wings unfold ", "label" : 0},
       {"paragraph" : "Me siento y espero ¿Un ángel contempla mi destino? Y ¿saben Los lugares a donde vamos Cuando somos viejos y grises? Porque me han dicho Que la salvación deja desplegar sus alas", "label" : 1},
       {"paragraph" : "Dragons are mythical creatures that have captured human imagination for centuries. These majestic beings are often depicted as powerful, fire-breathing creatures with scales and wings. In many cultures, dragons symbolize strength, wisdom, and even protection. Legends of brave knights facing off against fearsome dragons are woven into the fabric of folklore. Whether seen as fearsome adversaries or wise guardians, dragons continue to inspire stories, art, and a sense of awe across the world.", "label" : 0},
       {"paragraph" : "Los dragones son criaturas míticas que han capturado la imaginación humana durante siglos. Estos majestuosos seres a menudo se representan como criaturas poderosas que escupen fuego, con escamas y alas. En muchas culturas, los dragones simbolizan fuerza, sabiduría e incluso protección. Leyendas de valientes caballeros enfrentándose a dragones temibles están tejidas en el tejido del folclore. Ya sean vistos como adversarios temibles o guardianes sabios, los dragones continúan inspirando historias, arte y un sentido de asombro en todo el mundo.", "label" : 1},
       {"paragraph" : "Let me share a story about the time I got lost. I was in a new city, and suddenly, I found myself in a labyrinth of narrow alleys. No map, GPS acting up. It was nerve-wracking, but strangely exciting. Turns out, getting lost led me to hidden cafes, street art, and a chat with a local artist. Eventually, I found my way back, feeling accomplished and more adventurous", "label" : 0},
       {"paragraph" : "Permíteme contarte sobre cuando me perdí. Estaba en una ciudad nueva y, de repente, me encontré en un laberinto de callejones estrechos. Sin mapa, GPS fallando. Fue estresante pero extrañamente emocionante. Resulta que perderme me llevó a cafés escondidos, arte callejero y una charla con un artista local. Eventualmente, encontré mi camino de regreso, sintiéndome realizado y más aventurero", "label" : 1},
       {"paragraph" : "Let me tell you about my recent holiday. It was a much-needed break from the routine. I packed my bags, hopped on a plane, and landed in a place I'd only dreamed of. From exploring local markets to lounging on sandy beaches, every day was an adventure. The best part? Meeting people from all over the world, sharing stories, and making memories that will last a lifetime. As the trip came to an end, I felt rejuvenated and grateful for the experience", "label" : 0},
       {"paragraph" : "Déjame contarte sobre mis últimas vacaciones. Fue un descanso muy necesario de la rutina. Empaqué mis maletas, abordé un avión y aterricé en un lugar que solo había soñado. Desde explorar mercados locales hasta descansar en playas de arena, cada día fue una aventura. ¿Lo mejor? Conocer gente de todo el mundo, compartir historias y crear recuerdos que durarán toda la vida. A medida que el viaje llegaba a su fin, me sentí renovado y agradecido por la experiencia.", "label" : 1},
       {"paragraph" : "Let me share this amazing party I went to. It was an absolute blast! The energy was electric, and the music had everyone dancing from the moment they walked in. There were colorful decorations, and people were dressed up in the most creative outfits. Laughter and chatter filled the air as friends, old and new, mingled and celebrated. It was one of those nights where time seemed to fly, and we made memories that will keep us smiling for a long time", "label" : 0},
       {"paragraph" : "Permíteme contarte sobre una fiesta increíble a la que fui. ¡Fue una explosión total! La energía era eléctrica y la música hizo que todos bailaran desde el momento en que entraron. Había decoraciones coloridas y la gente iba vestida con los atuendos más creativos. Risas y charlas llenaban el ambiente mientras amigos, viejos y nuevos, se mezclaban y celebraban. Fue una de esas noches en las que el tiempo parecía volar y creamos recuerdos que nos harán sonreír durante mucho tiempo", "label" : 1}]
       
       
       
testData = [ {"paragraph" : "Make it make sense, I Can't hide a heart in a black tint, I You were off the bullshit and the tablets Under 21, both savage All these blurry nights feel the same to me Heart full of hate, no vacancy Only one you gonna blame when it's over Can't look me in my eyes when you sober Hey, I'm the one you call when you feelin' low Running up a check just to help you cope", "label" : 0},
              {"paragraph" : "Que tenga sentido, yo No puedo ocultar un corazón en un tono oscuro, yo Tú estabas fuera de las tonterías y las pastillas Menos de 21, ambos salvajes Todas estas noches borrosas se sienten igual para mí Corazón lleno de odio, no hay disponibilidad Solo a mí me culparás cuando termine No puedes mirarme a los ojos cuando estás sobrio Oye, soy el que llamas cuando te sientes bajo Acumulando un cheque solo para ayudarte a sobrellevar", "label" : 1},
              {"paragraph" : "Sweet days of summer, the jasmines in bloom July is dressed up and playing her tune When I come home from a hard day's work And you're waiting there, not a care in the world See the smile waiting in the kitchen Food cooking on a plate for two Feel the arms reaching out to hold me In the evening when the day is through  translate to spanish", "label" : 0},
              {"paragraph" : "Dulces días de verano, los jazmines florecen Julio se viste y toca su melodía Cuando vuelvo a casa después de un día de trabajo duro Y estás allí esperando, sin preocupación en el mundo Veo la sonrisa esperando en la cocina Comida cocinando en un plato para dos Siento los brazos extendiéndose para abrazarme Por la tarde cuando el día ha terminado.", "label" : 1},
              {"paragraph" : "Technology has revolutionized the way we interact and live. From the smartphones we carry in our pockets to automation in industry, technology has transformed our society. While it brings conveniences and advancements, it also poses ethical and privacy challenges that we must address responsibly.", "label" : 0},
              {"paragraph" : "La tecnología ha revolucionado la forma en que interactuamos y vivimos. Desde los teléfonos inteligentes que llevamos en nuestros bolsillos hasta la automatización en la industria, la tecnología ha transformado nuestra sociedad. Aunque trae comodidades y avances, también plantea desafíos éticos y de privacidad que debemos abordar de manera responsable.", "label" : 1},
              {"paragraph" : "Gastronomy is an art that combines flavors, textures, and cultures in every dish. From the simplicity of local cuisine to the creativity of renowned chefs, food is a unique expression of identity. Exploring the cuisine of different regions allows us to travel through our senses and understand the importance of food in culture.", "label" : 0},
              {"paragraph" : "La gastronomía es un arte que combina sabores, texturas y culturas en cada plato. Desde la sencillez de la cocina local hasta la creatividad de los chefs de renombre, la comida es una expresión única de identidad. Explorar la gastronomía de diferentes regiones nos permite viajar a través de los sentidos y comprender la importancia de la comida en la cultura.", "label" : 1},
              {"paragraph" : "Education is the foundation of personal growth and the development of prosperous societies. It provides knowledge, skills, and tools to face challenges. By investing in the education of future generations, we build a brighter and more equitable future where every individual can reach their full potential.", "label" : 0},
              {"paragraph" : "La educación es la base del crecimiento personal y el desarrollo de sociedades prósperas. Proporciona conocimiento, habilidades y herramientas para enfrentar desafíos. Al invertir en la educación de las generaciones futuras, construimos un futuro más brillante y equitativo donde cada individuo puede alcanzar su máximo potencial.", "label" : 1},
              {"paragraph" : "I know love is all I got I just hope to god she got good taste Could put you on some shit you never seen Could play a couple songs that you could dance to I hope you know she can't compete with me", "label" : 0},
              {"paragraph" : "Sé que el amor es todo lo que tengo. Solo espero que Dios haya dado buen gusto a ella. Podría ponerte en algo que nunca has visto. Podría tocar un par de canciones a las que podrías bailar. Espero que sepas que ella no puede competir conmigo.", "label" : 1},
              {"paragraph" : "hi  i love ice cream, dogs are my favourite pet i am turing 21 years old next year", "label" : 0},
              {"paragraph" : "Hola me encanta el helado los perros son mi mascota favorita y cumpliré 21 años el próximo año", "label" : 1},
              {"paragraph" : "there were too many people at my house last night it made me very upset and i cried a lot", "label" : 0},
              {"paragraph" : "Anoche había demasiada gente en mi casa, me puso muy triste y lloré mucho", "label" : 1}]
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
